name: clang-format verification

on: [push, workflow_dispatch]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'RetroGraph'
            exclude: 'resource\.h$'
          - check: 'RetroGraphDLL'
            exclude: 'resource\.h$'
          - check: 'RetroGraphTests'
    steps:
    - uses: actions/checkout@v3
    - name: clang-format Check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: ${{ matrix.path['check'] }}
        include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|(ixx)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu))$'
        exclude-regex: ${{ matrix.path['exclude'] }}
